version : '3'

services:
    todolist:
        build: .
        ports:
            - 8888:8888
        environment:
            - APP_HOST=0.0.0.0
            - APP_PORT=8888
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    redis:
        image: "redis:alpine"
        hostname: redis
        ports:
            - 6379:6379
